# Generated by Django 3.2.25 on 2025-08-16 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_remove_therapist_specialization'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='therapist',
            options={'ordering': ['-created_at'], 'verbose_name': '按摩師', 'verbose_name_plural': '按摩師'},
        ),
        migrations.AlterField(
            model_name='therapist',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='line_id',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Line ID'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='name',
            field=models.CharField(max_length=100, verbose_name='姓名'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='nick_name',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='暱稱'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='電話'),
        ),
        migrations.AlterField(
            model_name='therapist',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
    ]
