# Generated by Django 3.2.25 on 2025-08-17 11:28

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_auto_20250817_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='page_view_data',
            field=models.TextField(blank=True, null=True),
        )
    ]