# Generated by Django 3.2.25 on 2025-08-17 11:40

from django.db import migrations, models

def create_demo_store(apps, schema_editor):
    Store = apps.get_model('panel', 'Store')

class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0005_store_page_view_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='password',
            field=models.CharField(max_length=128),
        ),
    ]
