# panel/migrations/0007_auto_20250817_1230.py
# Generated by Django 3.2.25 on 2025-08-17 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.contrib.auth.hashers import make_password


def create_default_store(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Store = apps.get_model('panel', 'Store')

    # 1) 建一個預設用戶
    user, _ = User.objects.get_or_create(
        username="default_store",
        defaults={
            "email": "demo@store.com",
            "password": make_password("admin"),
        },
    )

    # 2) 建一個預設店家（若不存在）
    store, created = Store.objects.get_or_create(
        user=user,
        defaults={
            "name": "預設店家",
            "address": "台北市測試路 123 號",
            "phone": "0900000000",
        },
    )

    # 3)（可選）把現有沒有綁 user 的 Store 先暫時綁到這個 user（若你不想這樣做，可以刪掉這段）
    # for s in Store.objects.filter(user__isnull=True):
    #     s.user = user
    #     s.save()


def remove_default_store(apps, schema_editor):
    User = apps.get_model(settings.AUTH_USER_MODEL)
    Store = apps.get_model('panel', 'Store')
    try:
        user = User.objects.get(username="default_store")
        Store.objects.filter(user=user).delete()
        user.delete()
    except User.DoesNotExist:
        pass


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0006_auto_20250817_1140'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='store',
            options={'verbose_name': '店家', 'verbose_name_plural': '店家'},
        ),
        migrations.RemoveField(
            model_name='store',
            name='email',
        ),
        migrations.RemoveField(
            model_name='store',
            name='password',
        ),
        # ⚠ 先新增成 nullable，避免舊資料觸發 FK 預設值
        migrations.AddField(
            model_name='store',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='store',
                to=settings.AUTH_USER_MODEL,
                null=True, blank=True,
            ),
        ),
        migrations.AddField(
            model_name='therapist',
            name='bio',
            field=models.TextField(blank=True, null=True, verbose_name='介紹'),
        ),
        migrations.AddField(
            model_name='therapist',
            name='enabled',
            field=models.BooleanField(default=True, verbose_name='啟用'),
        ),
        migrations.AlterField(
            model_name='store',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='建立時間'),
        ),
        migrations.AlterField(
            model_name='store',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新時間'),
        ),
        # 建預設使用者與店家
        migrations.RunPython(create_default_store, remove_default_store),
        # 最後把欄位收緊為必填
        migrations.AlterField(
            model_name='store',
            name='user',
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='store',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
