# Generated by Django 3.2.25 on 2025-08-17 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_auto_20250817_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='therapist',
            name='is_deleted',
            field=models.BooleanField(default=False, verbose_name='已刪除'),
        ),
    ]
