# Generated by Django 3.2.25 on 2025-08-17 17:04

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_therapist_is_deleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceSurvey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 星'), (2, '2 星'), (3, '3 星'), (4, '4 星'), (5, '5 星')], default=5, verbose_name='星級')),
                ('comment', models.TextField(blank=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='填寫時間')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_surveys', to='panel.therapist')),
            ],
            options={
                'verbose_name': '服務問卷',
                'verbose_name_plural': '服務問卷',
                'ordering': ['-created_at'],
            },
        ),
    ]
