# Generated by Django 3.2.25 on 2025-08-18 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0009_servicesurvey'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassagePlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='方案名稱')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='方案價格')),
                ('duration', models.PositiveIntegerField(verbose_name='時間長度（分鐘）')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='massage_plans', to='panel.store', verbose_name='店家')),
            ],
            options={
                'verbose_name': '按摩方案',
                'verbose_name_plural': '按摩方案',
                'ordering': ['-created_at'],
            },
        ),
    ]
