# Generated by Django 3.2.25 on 2025-08-18 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0010_massageplan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=255, verbose_name='客戶姓名')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='客戶電話')),
                ('appointment_time', models.DateTimeField(verbose_name='預約時間')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('massage_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='panel.massageplan', verbose_name='預約的方案')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='panel.store', verbose_name='店家')),
                ('therapist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='panel.therapist', verbose_name='指定的師傅')),
            ],
            options={
                'verbose_name': '預約',
                'verbose_name_plural': '預約',
                'ordering': ['-appointment_time'],
            },
        ),
    ]
