# Generated by Django 3.2.25 on 2025-08-18 06:03

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0011_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MassageInvitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_time', models.DateTimeField(verbose_name='可預約的時間區間')),
                ('discount_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='特價')),
                ('slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='網址slug')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='多少人點開')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='備註')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='建立時間')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新時間')),
                ('massage_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='panel.massageplan', verbose_name='按摩方案')),
                ('therapist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='panel.therapist', verbose_name='師傅')),
            ],
            options={
                'verbose_name': '按摩邀請',
                'verbose_name_plural': '按摩邀請',
                'ordering': ['-created_at'],
            },
        ),
    ]
