# Generated by Django 3.2.25 on 2025-08-18 09:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0012_massageinvitation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massageinvitation',
            name='available_time',
        ),
        migrations.AddField(
            model_name='massageinvitation',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='結束時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massageinvitation',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='開始時間'),
            preserve_default=False,
        ),
    ]
