# Generated by Django 3.2.25 on 2025-08-18 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_auto_20250818_0949'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='備註'),
        ),
    ]
