# Generated by Django 3.2.25 on 2025-08-18 11:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0014_reservation_notes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='massageinvitation',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='massageinvitation',
            name='start_time',
        ),
        migrations.AddField(
            model_name='massageinvitation',
            name='available_end',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='可預約結束時間'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='massageinvitation',
            name='available_start',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='可預約開始時間'),
            preserve_default=False,
        ),
    ]
